//api calling
export const API_CALLING = "API_CALLING"

//handle error
export const HANDLE_ERROR = "HANDLE_ERROR"
export const HANDLE_GET_ALL_JOB_GROUP_ERROR = "HANDLE_GET_JOB_GROUP_ALL_ERROR"
export const HANDLE_GET_ALL_JOB_ERROR = "HANDLE_GET_ALL_JOB_ERROR"
export const HANDLE_GET_ALL_TASK_ERROR = "HANDLE_GET_TASK_ALL_ERROR"
export const HANDLE_GET_ALL_MEMBER_JOB_ERROR = "HANDLE_GET_ALL_MEMBER_JOB_ERROR"
export const HANDLE_GET_ALL_COMMENT_ERROR = "HANDLE_GET_ALL_COMMENT_ERROR"
export const HANDLE_GET_ALL_HISTORY_ERROR = "HANDLE_GET_ALL_HISTORY_ERROR"

//types about user
export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_LOGIN = "USER_LOGIN"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const UPDATE_NAME = "UPDATE_NAME"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const UPDATE_PASSWORD_ERROR= "UPDATE_PASSWORD_ERROR"

//types about project
export const GET_ALL_PROJECT = "GET_ALL_PROJECT"
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT'
export const GET_PROJECT_WITH_ID = "GET_PROJECT_WITH_ID"
export const UPDATE_PROJECT_NAME = "UPDATE_PROJECT_NAME"
export const DELETE_PROJECT = "DELETE_PROJECT"

//types about users of a project
export const GET_PROJECT_USER = "GET_PROJECT_USER"
export const ADD_PROJECT_USER = "ADD_PROJECT_USER"
export const DELETE_PROJECT_USER = "DELETE_PROJECT_USER"

//types about member
export const GET_ALL_MEMBER = "GET_ALL_MEMBER"
export const DELETE_MEMBER = "DELETE_MEMBER"

//types about job_group
export const GET_ALL_JOB_GROUP = "GET_ALL_JOB_GROUP"
export const GET_JOB_GROUP_WITH_ID = "GET_JOB_GROUP_WITH_ID"
export const ADD_NEW_JOB_GROUP = 'ADD_NEW_JOB_GROUP'
export const UPDATE_JOB_GROUP_NAME = "UPDATE_JOB_GROUP_NAME"
export const DELETE_JOB_GROUP = "DELETE_JOB_GROUP"

//types about job
export const GET_ALL_JOB = "GET_ALL_JOB"
export const GET_JOB_WITH_ID = "GET_JOB_WITH_ID"
export const ADD_NEW_JOB = 'ADD_NEW_JOB'
export const UPDATE_JOB = "UPDATE_JOB"
export const DELETE_JOB = "DELETE_JOB"
export const SHOW_HISTORY = "SHOW_HISTORY"

//types about task
export const GET_ALL_TASK = "GET_ALL_TASK"
export const GET_TASK_WITH_ID = "GET_TASK_WITH_ID"
export const ADD_NEW_TASK = 'ADD_NEW_TASK'
export const UPDATE_TASK = "UPDATE_TASK"
export const DELETE_TASK = "DELETE_TASK"

//types about members of job
export const GET_ALL_MEMBER_JOB = "GET_ALL_MEMBER_JOB"
export const ADD_NEW_MEMBER_JOB = "ADD_NEW_MEMBER_JOB"
export const DELETE_MEMBER_JOB = "DELETE_MEMBER_JOB"

//types about comment
export const GET_ALL_COMMENT = "GET_ALL_COMMENT"
export const GET_COMMENT_WITH_ID = "GET_COMMENT_WITH_ID"
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT'
export const UPDATE_COMMENT = "UPDATE_COMMENT"
export const DELETE_COMMENT = "DELETE_COMMENT"

//types about personal project
export const GET_ALL_PERSONAL_PROJECT = "GET_ALL_PERSONAL_PROJEC" 
export const GET_PERSONAL_PROJECT_WITH_ID = "GET_PERSONAL_PROJECT_WITH_ID"
export const ADD_NEW_PERSONAL_PROJECT = 'ADD_NEW_PERSONAL_PROJECT'
export const UPDATE_PERSONAL_PROJECT_NAME = "UPDATE_PERSONAL_PROJECT_NAME"
export const DELETE_PERSONAL_PROJECT = "DELETE_PESONAL_PROJECT"
